obstacle_range: 1.0
raytrace_range: 2.0
footprint: [[0.2, 0.12], [0.2, -0.12], [-0.2, -0.12], [-0.2, 0.12]]
#inflation_radius: 0.05
max_obstacle_height: 0.4
min_obstacle_height: 0.1
observation_sources: scan
scan: {data_type: LaserScan, topic: /scan, marking: true, clearing: true, expected_update_rate: 0}
