global_costmap:
   global_frame: map 
#用来表示全局代价地图需要在哪个参考系下运行，这里选择了map参考系
 
   robot_base_frame: base_link
#参数用来表示代价地图可以参考的机器人本体的坐标系
 
   update_frequency: 1.0
#参数用来决定全局地图信息更新的频率，单位是Hz
 
   publish_frequency: 1.0
 
   static_map: true
#参数用来决定代价地图是否需要根据map_server提供的地图信息进行初始化，如果不需要使用已有的地图这最好设置为false
 
   rolling_window: false
   resolution: 0.01 #分辨率
   transform_tolerance: 1.0 #转换容忍
   map_type: costmap #地图类型
